name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: "Zadanie 10/frontend"

      - name: Build Angular App
        run: npm run build
        working-directory: "Zadanie 10/frontend"

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore "Zadanie 10/backend/backend.sln"

    - name: Build
      run: dotnet build "Zadanie 10/backend/backend.sln" --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test "Zadanie 10/backend/backend.sln" --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish "Zadanie 10/backend/backend.sln" -c Release -o ./publish